Update solution.py
GDSC-CEC/HacktoberFest-2022-Python pull request #78
Opened 2022-10-23 13:38 UTC by pranavgupta2603

2022-10-23 13:54 UTC, Anamaya1729 requested changes
Your solution is not recursive, change the directory of your solution or your solution. Otherwise your code is correct.

2022-10-23 17:14 UTC, pranavgupta2603 commented
Changed the directory. Does this work?

2022-10-24 08:38 UTC, pranavgupta2603 commented
Hi. Does the solution work now or do I need more changes?

2022-10-24 08:53 UTC, Anamaya1729 approved these changes

2022-10-24 08:53 UTC, merged